CREATE TABLE HUB_TYPES(ID INTEGER, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE HUB_ITEMS(ID INTEGER, CODE VARCHAR(10), PRIMARY KEY (ID));
CREATE TABLE LNK_TYPES_ITEMS(ID INTEGER, HUB_TYPE INTEGER, HUB_ITEM INTEGER, PRIMARY KEY (ID));
CREATE TABLE SAT_BOOKS(ID INTEGER, HUB_ITEM INTEGER, AUTHOR VARCHAR(50), NAME VARCHAR(200), SERIES VARCHAR(40), GENRE VARCHAR(40), PUBLISHER VARCHAR(40), PBYEAR INTEGER, NOTE VARCHAR(256), PRIMARY KEY (ID));