package com.github.yard01.rx.introduction;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ExampleLauncher {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main (String[] args) {
    	RxDemonstrator rxdf = new RxDemonstrator();
    	rxdf.demonstrate();
    	System.out.println();
    }
}
