/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.github.yard01.rx.introduction.ExampleLauncher;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        ExampleLauncher classUnderTest = new ExampleLauncher();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
